export const PRODUCTCATEGORY_TREE_REQUEST = 'PRODUCTCATEGORY_TREE_REQUEST';
export const PRODUCTCATEGORY_TREE_SUCCESS = 'PRODUCTCATEGORY_TREE_SUCCESS';
export const PRODUCTCATEGORY_TREE_FAIL = 'PRODUCTCATEGORY_TREE_FAIL';