export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_UPDATE_TOKEN = "USER_UPDATE_TOKEN";
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_REMEMBER = "USER_REMEMBER";
export const USER_NOT_REMEMBER = "USER_NOT_REMEMBER";
export const USER_SIGNIN_REQUEST_PERMANENT = "USER_SIGNIN_REQUEST_PERMANENT";
export const USER_SIGNIN_SUCCESS_PERMANENT = "USER_SIGNIN_SUCCESS_PERMANENT";
export const USER_SIGNIN_FAIL_PERMANENT = "USER_SIGNIN_FAIL_PERMANENT";
export const USER_UPDATE_TOKEN_PERMANENT = "USER_UPDATE_TOKEN_PERMANENT";
export const USER_GET_ALL_INFO = "USER_GET_ALL_INFO";
export const USER_ADD_TO_CART_SUCCESS = "USER_ADD_TO_CART_SUCCESS";
export const USER_ADD_TO_CART_SUCCESS_PERMANENT = "USER_ADD_TO_CART_SUCCESS_PERMANENT";
export const USER_ADD_TO_CART_FAIL = "USER_ADD_TO_CART_FAIL";
export const USER_UPDATE_CART = "USER_UPDATE_CART";
export const USER_DELETE_CARTS = "USER_DELETE_CARTS";
export const USER_PLACEORDER_REQUEST = "USER_CHECKOUT_REQUEST";
export const USER_PLACEORDER_DONE = "USER_DONE";
export const USER_DELETE_ORDER = "USER_DELETE_ORDER";


class typeOfSignUP{
    static customer = 'ROLE_CUSTOMER'
    static seller = 'ROLE_SELLER'
}
export {typeOfSignUP}